"""Where agent processes run.

Each task has a directory on the server's disk:

    <data_dir>/tasks/<id>/
        repo/            the git workspace the agent edits
        home/            the agent's HOME (CLI config, session transcripts)
        turns/<n>.sh     wrapper that runs the agent for turn n
        turns/<n>.prompt / .jsonl / .pid / .exit

The agent runs detached and writes its output to turns/<n>.jsonl, which the server tails.
So a turn keeps running if the browser closes or the server restarts, and the server picks
up where it left off. Git operations happen on the server, against the same directory.
"""

import asyncio
import contextlib
import os
import shlex
import signal
from pathlib import Path
from typing import Protocol

from app.config import Settings

WRAPPER = """#!/bin/sh
# Runs one agent turn. Generated by Zimua; see app/tasks/sandbox.py.
cd "$(dirname "$0")/../repo" || exit 1
{env_exports}
{command} < ../turns/{n}.prompt > ../turns/{n}.jsonl 2>&1 &
child=$!
echo $child > ../turns/{n}.pid
wait $child
echo $? > ../turns/{n}.exit.tmp && mv ../turns/{n}.exit.tmp ../turns/{n}.exit
"""


def task_dir(settings: Settings, task_id: str) -> Path:
    return (settings.data_dir / "tasks" / task_id).resolve()


def write_turn_script(
    root: Path, n: int, argv: list[str], env: dict[str, str], prompt: str, home: str
) -> Path:
    turns = root / "turns"
    turns.mkdir(parents=True, exist_ok=True)
    (turns / f"{n}.prompt").write_text(prompt)
    exports = {"HOME": home, **env}
    script = turns / f"{n}.sh"
    script.write_text(
        WRAPPER.format(
            n=n,
            command=shlex.join(argv),
            env_exports="\n".join(f"export {k}={shlex.quote(v)}" for k, v in exports.items()),
        )
    )
    # The script holds credentials (e.g. the Claude token); keep it private.
    script.chmod(0o700)
    return script


class Sandbox(Protocol):
    async def prepare(self, task_id: str) -> None:
        """Makes the task's environment ready to run turns (e.g. starts its container)."""

    async def launch(self, task_id: str, n: int) -> None:
        """Starts turns/<n>.sh detached and returns immediately."""

    async def is_alive(self, task_id: str, pid: int) -> bool: ...

    async def interrupt(self, task_id: str, pid: int) -> None: ...

    async def destroy(self, task_id: str) -> None: ...

    def home(self, task_id: str) -> str:
        """The agent's HOME, as seen by the agent."""
        ...


class LocalSandbox:
    """Runs agents as plain processes on this machine. No isolation from the server."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    def home(self, task_id: str) -> str:
        return str(task_dir(self._settings, task_id) / "home")

    async def prepare(self, task_id: str) -> None:
        (task_dir(self._settings, task_id) / "home").mkdir(parents=True, exist_ok=True)

    async def launch(self, task_id: str, n: int) -> None:
        script = task_dir(self._settings, task_id) / "turns" / f"{n}.sh"
        # Double fork: the intermediate shell exits at once, leaving the turn orphaned in its
        # own session. Nothing the server does on shutdown (asyncio kills its own children
        # when the loop closes) can then stop it, and no zombie is left behind.
        proc = await asyncio.create_subprocess_exec(
            "sh",
            "-c",
            'sh "$0" </dev/null >/dev/null 2>&1 &',
            str(script),
            start_new_session=True,
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await proc.wait()

    async def is_alive(self, task_id: str, pid: int) -> bool:
        try:
            os.kill(pid, 0)
        except ProcessLookupError:
            return False
        except PermissionError:
            return True
        return True

    async def interrupt(self, task_id: str, pid: int) -> None:
        with contextlib.suppress(ProcessLookupError):
            os.kill(pid, signal.SIGTERM)

    async def destroy(self, task_id: str) -> None:
        pass


class DockerSandbox:
    """One long-lived container per task, from the runner image, with the task directory
    bind-mounted at /workspace. Needs the docker CLI and access to the Docker socket."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    @staticmethod
    def container(task_id: str) -> str:
        return f"zimua-task-{task_id}"

    def home(self, task_id: str) -> str:
        return "/workspace/home"

    async def _docker(self, *args: str, check: bool = True) -> str:
        proc = await asyncio.create_subprocess_exec(
            "docker",
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        out, err = await proc.communicate()
        if check and proc.returncode != 0:
            raise RuntimeError(err.decode(errors="replace").strip() or f"docker {args[0]} failed")
        return out.decode(errors="replace")

    async def prepare(self, task_id: str) -> None:
        root = task_dir(self._settings, task_id)
        (root / "home").mkdir(parents=True, exist_ok=True)
        name = self.container(task_id)
        state = (
            await self._docker("inspect", "-f", "{{.State.Running}}", name, check=False)
        ).strip()
        if state == "true":
            return
        if state == "false":
            await self._docker("start", name)
            return
        await self._docker(
            "run", "--detach", "--name", name,
            "--label", "zimua.task=" + task_id,
            "--user", f"{os.getuid()}:{os.getgid()}",
            "--volume", f"{root}:/workspace",
            "--workdir", "/workspace/repo",
            "--env", "HOME=/workspace/home",
            "--init",
            self._settings.runner_image,
            "sleep", "infinity",
        )  # fmt: skip

    async def launch(self, task_id: str, n: int) -> None:
        await self.prepare(task_id)
        await self._docker(
            "exec", "--detach", self.container(task_id), "sh", f"/workspace/turns/{n}.sh"
        )

    async def is_alive(self, task_id: str, pid: int) -> bool:
        out = await self._docker(
            "exec", self.container(task_id), "sh", "-c", f"kill -0 {pid} && echo yes",
            check=False,
        )  # fmt: skip
        return out.strip() == "yes"

    async def interrupt(self, task_id: str, pid: int) -> None:
        await self._docker("exec", self.container(task_id), "kill", "-TERM", str(pid), check=False)

    async def destroy(self, task_id: str) -> None:
        await self._docker("rm", "--force", self.container(task_id), check=False)


def make_sandbox(settings: Settings) -> Sandbox:
    return DockerSandbox(settings) if settings.sandbox == "docker" else LocalSandbox(settings)
